/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedTiposDeQuartoIndexRouteImport } from './routes/_authenticated/tipos-de-quarto.index'
import { Route as AuthenticatedReservasIndexRouteImport } from './routes/_authenticated/reservas.index'
import { Route as AuthenticatedQuartosIndexRouteImport } from './routes/_authenticated/quartos.index'
import { Route as AuthenticatedHospedesIndexRouteImport } from './routes/_authenticated/hospedes.index'
import { Route as AuthenticatedTiposDeQuartoNovoRouteImport } from './routes/_authenticated/tipos-de-quarto.novo'
import { Route as AuthenticatedReservasNovoRouteImport } from './routes/_authenticated/reservas.novo'
import { Route as AuthenticatedQuartosNovoRouteImport } from './routes/_authenticated/quartos.novo'
import { Route as AuthenticatedHospedesNovoRouteImport } from './routes/_authenticated/hospedes.novo'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedTiposDeQuartoIdEditarRouteImport } from './routes/_authenticated/tipos-de-quarto.$id.editar'
import { Route as AuthenticatedReservasIdEditarRouteImport } from './routes/_authenticated/reservas.$id.editar'
import { Route as AuthenticatedQuartosIdEditarRouteImport } from './routes/_authenticated/quartos.$id.editar'
import { Route as AuthenticatedHospedesIdEditarRouteImport } from './routes/_authenticated/hospedes.$id.editar'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTiposDeQuartoIndexRoute =
  AuthenticatedTiposDeQuartoIndexRouteImport.update({
    id: '/tipos-de-quarto/',
    path: '/tipos-de-quarto/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservasIndexRoute =
  AuthenticatedReservasIndexRouteImport.update({
    id: '/reservas/',
    path: '/reservas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuartosIndexRoute =
  AuthenticatedQuartosIndexRouteImport.update({
    id: '/quartos/',
    path: '/quartos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospedesIndexRoute =
  AuthenticatedHospedesIndexRouteImport.update({
    id: '/hospedes/',
    path: '/hospedes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTiposDeQuartoNovoRoute =
  AuthenticatedTiposDeQuartoNovoRouteImport.update({
    id: '/tipos-de-quarto/novo',
    path: '/tipos-de-quarto/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservasNovoRoute =
  AuthenticatedReservasNovoRouteImport.update({
    id: '/reservas/novo',
    path: '/reservas/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuartosNovoRoute =
  AuthenticatedQuartosNovoRouteImport.update({
    id: '/quartos/novo',
    path: '/quartos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospedesNovoRoute =
  AuthenticatedHospedesNovoRouteImport.update({
    id: '/hospedes/novo',
    path: '/hospedes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTiposDeQuartoIdEditarRoute =
  AuthenticatedTiposDeQuartoIdEditarRouteImport.update({
    id: '/tipos-de-quarto/$id/editar',
    path: '/tipos-de-quarto/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservasIdEditarRoute =
  AuthenticatedReservasIdEditarRouteImport.update({
    id: '/reservas/$id/editar',
    path: '/reservas/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuartosIdEditarRoute =
  AuthenticatedQuartosIdEditarRouteImport.update({
    id: '/quartos/$id/editar',
    path: '/quartos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHospedesIdEditarRoute =
  AuthenticatedHospedesIdEditarRouteImport.update({
    id: '/hospedes/$id/editar',
    path: '/hospedes/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/hospedes/novo': typeof AuthenticatedHospedesNovoRoute
  '/quartos/novo': typeof AuthenticatedQuartosNovoRoute
  '/reservas/novo': typeof AuthenticatedReservasNovoRoute
  '/tipos-de-quarto/novo': typeof AuthenticatedTiposDeQuartoNovoRoute
  '/hospedes/': typeof AuthenticatedHospedesIndexRoute
  '/quartos/': typeof AuthenticatedQuartosIndexRoute
  '/reservas/': typeof AuthenticatedReservasIndexRoute
  '/tipos-de-quarto/': typeof AuthenticatedTiposDeQuartoIndexRoute
  '/hospedes/$id/editar': typeof AuthenticatedHospedesIdEditarRoute
  '/quartos/$id/editar': typeof AuthenticatedQuartosIdEditarRoute
  '/reservas/$id/editar': typeof AuthenticatedReservasIdEditarRoute
  '/tipos-de-quarto/$id/editar': typeof AuthenticatedTiposDeQuartoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/hospedes/novo': typeof AuthenticatedHospedesNovoRoute
  '/quartos/novo': typeof AuthenticatedQuartosNovoRoute
  '/reservas/novo': typeof AuthenticatedReservasNovoRoute
  '/tipos-de-quarto/novo': typeof AuthenticatedTiposDeQuartoNovoRoute
  '/hospedes': typeof AuthenticatedHospedesIndexRoute
  '/quartos': typeof AuthenticatedQuartosIndexRoute
  '/reservas': typeof AuthenticatedReservasIndexRoute
  '/tipos-de-quarto': typeof AuthenticatedTiposDeQuartoIndexRoute
  '/hospedes/$id/editar': typeof AuthenticatedHospedesIdEditarRoute
  '/quartos/$id/editar': typeof AuthenticatedQuartosIdEditarRoute
  '/reservas/$id/editar': typeof AuthenticatedReservasIdEditarRoute
  '/tipos-de-quarto/$id/editar': typeof AuthenticatedTiposDeQuartoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/hospedes/novo': typeof AuthenticatedHospedesNovoRoute
  '/_authenticated/quartos/novo': typeof AuthenticatedQuartosNovoRoute
  '/_authenticated/reservas/novo': typeof AuthenticatedReservasNovoRoute
  '/_authenticated/tipos-de-quarto/novo': typeof AuthenticatedTiposDeQuartoNovoRoute
  '/_authenticated/hospedes/': typeof AuthenticatedHospedesIndexRoute
  '/_authenticated/quartos/': typeof AuthenticatedQuartosIndexRoute
  '/_authenticated/reservas/': typeof AuthenticatedReservasIndexRoute
  '/_authenticated/tipos-de-quarto/': typeof AuthenticatedTiposDeQuartoIndexRoute
  '/_authenticated/hospedes/$id/editar': typeof AuthenticatedHospedesIdEditarRoute
  '/_authenticated/quartos/$id/editar': typeof AuthenticatedQuartosIdEditarRoute
  '/_authenticated/reservas/$id/editar': typeof AuthenticatedReservasIdEditarRoute
  '/_authenticated/tipos-de-quarto/$id/editar': typeof AuthenticatedTiposDeQuartoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/calendario'
    | '/equipe'
    | '/invite/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/hospedes/novo'
    | '/quartos/novo'
    | '/reservas/novo'
    | '/tipos-de-quarto/novo'
    | '/hospedes/'
    | '/quartos/'
    | '/reservas/'
    | '/tipos-de-quarto/'
    | '/hospedes/$id/editar'
    | '/quartos/$id/editar'
    | '/reservas/$id/editar'
    | '/tipos-de-quarto/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/calendario'
    | '/equipe'
    | '/invite/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/hospedes/novo'
    | '/quartos/novo'
    | '/reservas/novo'
    | '/tipos-de-quarto/novo'
    | '/hospedes'
    | '/quartos'
    | '/reservas'
    | '/tipos-de-quarto'
    | '/hospedes/$id/editar'
    | '/quartos/$id/editar'
    | '/reservas/$id/editar'
    | '/tipos-de-quarto/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/_authenticated/calendario'
    | '/_authenticated/equipe'
    | '/invite/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/hospedes/novo'
    | '/_authenticated/quartos/novo'
    | '/_authenticated/reservas/novo'
    | '/_authenticated/tipos-de-quarto/novo'
    | '/_authenticated/hospedes/'
    | '/_authenticated/quartos/'
    | '/_authenticated/reservas/'
    | '/_authenticated/tipos-de-quarto/'
    | '/_authenticated/hospedes/$id/editar'
    | '/_authenticated/quartos/$id/editar'
    | '/_authenticated/reservas/$id/editar'
    | '/_authenticated/tipos-de-quarto/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  InviteTokenRoute: typeof InviteTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tipos-de-quarto/': {
      id: '/_authenticated/tipos-de-quarto/'
      path: '/tipos-de-quarto'
      fullPath: '/tipos-de-quarto/'
      preLoaderRoute: typeof AuthenticatedTiposDeQuartoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas/': {
      id: '/_authenticated/reservas/'
      path: '/reservas'
      fullPath: '/reservas/'
      preLoaderRoute: typeof AuthenticatedReservasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quartos/': {
      id: '/_authenticated/quartos/'
      path: '/quartos'
      fullPath: '/quartos/'
      preLoaderRoute: typeof AuthenticatedQuartosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospedes/': {
      id: '/_authenticated/hospedes/'
      path: '/hospedes'
      fullPath: '/hospedes/'
      preLoaderRoute: typeof AuthenticatedHospedesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tipos-de-quarto/novo': {
      id: '/_authenticated/tipos-de-quarto/novo'
      path: '/tipos-de-quarto/novo'
      fullPath: '/tipos-de-quarto/novo'
      preLoaderRoute: typeof AuthenticatedTiposDeQuartoNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas/novo': {
      id: '/_authenticated/reservas/novo'
      path: '/reservas/novo'
      fullPath: '/reservas/novo'
      preLoaderRoute: typeof AuthenticatedReservasNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quartos/novo': {
      id: '/_authenticated/quartos/novo'
      path: '/quartos/novo'
      fullPath: '/quartos/novo'
      preLoaderRoute: typeof AuthenticatedQuartosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospedes/novo': {
      id: '/_authenticated/hospedes/novo'
      path: '/hospedes/novo'
      fullPath: '/hospedes/novo'
      preLoaderRoute: typeof AuthenticatedHospedesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tipos-de-quarto/$id/editar': {
      id: '/_authenticated/tipos-de-quarto/$id/editar'
      path: '/tipos-de-quarto/$id/editar'
      fullPath: '/tipos-de-quarto/$id/editar'
      preLoaderRoute: typeof AuthenticatedTiposDeQuartoIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas/$id/editar': {
      id: '/_authenticated/reservas/$id/editar'
      path: '/reservas/$id/editar'
      fullPath: '/reservas/$id/editar'
      preLoaderRoute: typeof AuthenticatedReservasIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quartos/$id/editar': {
      id: '/_authenticated/quartos/$id/editar'
      path: '/quartos/$id/editar'
      fullPath: '/quartos/$id/editar'
      preLoaderRoute: typeof AuthenticatedQuartosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospedes/$id/editar': {
      id: '/_authenticated/hospedes/$id/editar'
      path: '/hospedes/$id/editar'
      fullPath: '/hospedes/$id/editar'
      preLoaderRoute: typeof AuthenticatedHospedesIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedHospedesNovoRoute: typeof AuthenticatedHospedesNovoRoute
  AuthenticatedQuartosNovoRoute: typeof AuthenticatedQuartosNovoRoute
  AuthenticatedReservasNovoRoute: typeof AuthenticatedReservasNovoRoute
  AuthenticatedTiposDeQuartoNovoRoute: typeof AuthenticatedTiposDeQuartoNovoRoute
  AuthenticatedHospedesIndexRoute: typeof AuthenticatedHospedesIndexRoute
  AuthenticatedQuartosIndexRoute: typeof AuthenticatedQuartosIndexRoute
  AuthenticatedReservasIndexRoute: typeof AuthenticatedReservasIndexRoute
  AuthenticatedTiposDeQuartoIndexRoute: typeof AuthenticatedTiposDeQuartoIndexRoute
  AuthenticatedHospedesIdEditarRoute: typeof AuthenticatedHospedesIdEditarRoute
  AuthenticatedQuartosIdEditarRoute: typeof AuthenticatedQuartosIdEditarRoute
  AuthenticatedReservasIdEditarRoute: typeof AuthenticatedReservasIdEditarRoute
  AuthenticatedTiposDeQuartoIdEditarRoute: typeof AuthenticatedTiposDeQuartoIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedHospedesNovoRoute: AuthenticatedHospedesNovoRoute,
  AuthenticatedQuartosNovoRoute: AuthenticatedQuartosNovoRoute,
  AuthenticatedReservasNovoRoute: AuthenticatedReservasNovoRoute,
  AuthenticatedTiposDeQuartoNovoRoute: AuthenticatedTiposDeQuartoNovoRoute,
  AuthenticatedHospedesIndexRoute: AuthenticatedHospedesIndexRoute,
  AuthenticatedQuartosIndexRoute: AuthenticatedQuartosIndexRoute,
  AuthenticatedReservasIndexRoute: AuthenticatedReservasIndexRoute,
  AuthenticatedTiposDeQuartoIndexRoute: AuthenticatedTiposDeQuartoIndexRoute,
  AuthenticatedHospedesIdEditarRoute: AuthenticatedHospedesIdEditarRoute,
  AuthenticatedQuartosIdEditarRoute: AuthenticatedQuartosIdEditarRoute,
  AuthenticatedReservasIdEditarRoute: AuthenticatedReservasIdEditarRoute,
  AuthenticatedTiposDeQuartoIdEditarRoute:
    AuthenticatedTiposDeQuartoIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  InviteTokenRoute: InviteTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
